language: node_js
node_js:
  - '6'
  - '6.0'
  - '6.1'
install: npm install
script: npm test -- --saucelabs
addons:
  sauce_connect:
    username: firebaseui
  jwt:
    secure: N2XxNudp1yIYrXZ1LIQVnVWW4L5doPIws6a10SHzxttigRXNDK2gQycVTN1MVwyVElVjPyyrLdsB9eRp0fSa0O6/MLc6tlbmt4cOT/zIi96ii3G6L5no9Yod8W5LAr4l2paB9apInghC2zetPGxCS4sW9vKEsIwzTIZZTBnq9AVfU0kpScgnD8/etiYljVTzXp36B65a2T9rXPXnhXKwYyX+TBRULJWhmHoM3FJwUxhMoa41XxxD1+0Zhd+lvBLzPjkRoUUJLR+JFpBDvjhtRkARPiAG+3r07ycrYZAMB87ZypBJOJBrUYA4KlxotPZc7jYEeAmiWJxDoZwwJQeyoI9J42fMEcdqzn7a6bm59jpKHXRwPNed2EY19BtBpXcYMjJRxLFSgWbrKw/hcqi9waaFBO/SXaCtUGPamxYSBHUaS1ljAR7omDkq2aeQAV2E4lgD9od3sgXGqCWzdl33erm4cWgjaNGVQlpNzBdG8zm3C870+x5+pvlsM2/lPCA0RIkIcA5uPmBmQlB8cgzfBCh0x5r6C9wl3TWGW9LaJAB9WZpgkmGk92A1sCnVRufaNYNJm8CwTxM2IK/3xWRc0bEdXpY3I4vA0uMelitWDI9wBIT+HN9TWPQUHzStjlP8PwBAZxf4ab2bB+GLEa5yUyiERK3iyHmX8gvFo14fPEw=
